version: '3.9'

services:
  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - ganache

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - backend
  
  ganache:
    build:
      context: ./ganache
      dockerfile: Dockerfile
    ports:
    - "8545:8545"
