version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ganache
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network
  
  ganache:
    build:
      context: ./ganache
      dockerfile: Dockerfile
    ports:
    - "8545:8545"
    networks: 
    - app_network

networks:
  app_network:
    driver: bridge